spring:
  config:
    activate:
      on-profile: local
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
