spring:
  config:
    activate:
      on-profile: local
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

sendgrid:
  api-key: ${SENDGRID_API_KEY:}
  from-email: ${SENDGRID_FROM_EMAIL:}
  from-name: ${SENDGRID_FROM_NAME:StaySphere}
