spring:
  config:
    activate:
      on-profile: local
    import: optional:file:../.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

staysphere:
  property-service-url: ${PROPERTY_SERVICE_URL:http://localhost:8082}
