spring:
  application:
    name: pricing-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/staysphere}
    username: ${SPRING_DATASOURCE_USERNAME:staysphere}
    password: ${SPRING_DATASOURCE_PASSWORD:staysphere123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: flyway_pricing_history
server:
  port: ${SERVER_PORT:8085}
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}
